services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: file:/app/database/database.db
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=file:/app/database/database.db
    volumes:
      - ./database:/app/database
