services:
  db:
    image: postgres:16-alpine
    container_name: chaos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chaos_api_db
    ports:
      - "5432:5432"
    volumes:
      - chaos_data:/var/lib/postgresql/data

volumes:
  chaos_data:
